version: '2'
services:
  osrm-backend:
    image: peterevans/osrm-backend:latest
    container_name: osrm-backend
    environment:
      - OSRM_PBF_URL=http://download.geofabrik.de/asia/iran-latest.osm.pbf
    volumes:
      - ./osrm-data:/osrm-data/
    restart: always
    ports:
      - "5000:5000"
  osm-nominatim:
    image: mediagis/nominatim
    command: /app/start.sh
    volumes:
      - ./nominatimdata/postgresdata:/var/lib/postgresql/9.5/main
    environment:
      - PBF_DATA='http://download.geofabrik.de/asia/iran-latest.osm.pbf'
    restart: always
    ports:
     - "7070:8080"
